### ISSUE TITLE
'The [ordinal number]' is always recognized as a date, even without the right context

### ISSUE THREAD

**Issue by stefanievonk** [facebook/duckling#217]
**curl -XPOST http://0.0.0.0:8000/parse --data 'locale=en_GB&text=The second test run shows the same bug.'**
[{"body":"The second","start":0,"value":{"values":[{"value":"2018-07-02T00:00:00.000-07:00","grain":"day","type":"value"},{"value":"2018-08-02T00:00:00.000-07:00","grain":"day","type":"value"},{"value":"2018-09-02T00:00:00.000-07:00","grain":"day","type":"value"}],"value":"2018-07-02T00:00:00.000-07:00","grain":"day","type":"value"},"end":10,"dim":"time","latent":false}]

**Comment by patapizza** [comment]
Thanks for reporting!

This is to catch days of month - we can use some heuristics and make it latent without more context to reduce the false positives rate.

**Comment by stefanievonk** [comment]
That would be very nice! Is this something we can help with?

**Comment by anaportela** [comment]
Hello! for me the cardinal numbers are always parsed as part of time.
examples:
house 1 on december 2013
house1 on december 2013
In these cases house_1 is another entity and the time should be the month of december 2013 but it recognizing the time as 1, 12, 2013.
What can I do to prevent this?

**Comment by patapizza** [comment]
Thanks for reporting @anaportela, I'll look into this.

**Comment by patapizza** [comment]
@anaportela This is now fixed. Thanks for your patience!

**Comment by anaportela** [comment]
Thank you for looking into this issue and for solving it so fast @patapizza

**Comment by anaportela** [comment]
Hello! @patapizza
I think the problem persisted. In sentences like:
"temperature of house 1 january 2016"
"temperature of house1 january 2016"
Where house_1 is a different entity, the time is recognized as 1,1,2016 and not as the month of January 2016.

**Comment by patapizza** [comment]
Hi @anaportela, these examples are outside of Duckling's scope: "1 january 2016" can be a date, so it will parse as much as possible, without taking into account the sentence context.
For higher precision, use in conjunction with a machine learning model to weed out false positives (e.g. using https://wit.ai).

**Comment by anaportela** [comment]
ok @patapizza I see! But I believe the previous "problem" is also still happening with the "on" after a number.

**Comment by patapizza** [comment]
Not sure what you mean. For both:
`house 1 on december 2013`
`house1 on december 2013`
The text `december 2013` is parsed, resolving to a monthly grain.

**Comment by xiaoyunwu** [comment]
curl -XPOST http://127.0.0.1:8000/parse --data 'locale=en_GB&text=the second&latent=True'

with latent = True, the second is not recognized as ordinal number for me, did I do something wrong? How can I get "the second/the second one" to be recognized as ordinal?

**Comment by chessai** [comment]
Use lowercase true, capital T won't decode

**Comment by xiaoyunwu** [comment]
> Use lowercase true, capital T won't decode

thanks for quick reply, but the following still does not work. Anything else?
curl -XPOST http://127.0.0.1:8000/parse --data 'locale=en_GB&text=the second&latent=true'

**Comment by xiaoyunwu** [comment]
@patapizza 
I did a bit more poking around, and I think it is a bug and it is not related to latent. I have modified line 111 of ExampleMain.hs to 
    options = Options {withLatent = True}

And if I do: 
 curl -XPOST http://0.0.0.0:8000/parse --data 'locale=en_GB&text=the second&dims=["ordinal"]'
the result is:
[{"body":"second","start":4,"value":{"value":2,"type":"value"},"end":10,"dim":"ordinal","latent":false}]
which means that ordinal is not latent. But as soon as I add time to dims, or remove dims all together, I only have time left. The ordinal part is gone.
